
export const ITEMS = [
    {
        id : 1,
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "velcore",
        material: "cotton",
        color: ["black","Blue","White","Gray","Red"],
        size: ["Small","Medium" ,"Large","X-Large"],
        price: "",
        mainImage: '/imgs/1.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree: "bullet filler three",
        vaiations:[]
    },


    {
        id : 2,
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "snapback",
        material: "cotton",
        color: ["black","Blue","White","Gray","Red"],
        size: ["Small","Medium" ,"Large"],
        price: 20.99,
        mainImage: '/imgs/2.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:0,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 3,
        name:'Pretty hat',
        frontShape: "flatBill",
        color: ["black","Blue","White","Gray","Red"],
        material: "cotton",
        color: "yellow",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/3.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:0,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 4,
        name:'Pretty hat',
        frontShape: "unstructured",
        Closure: "fitit",
        material: "cotton",
        color: "gray",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/4.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 5,
        name:'Pretty hat',
        frontShape: "slightly",
        Closure: "velcore",
        material: "cotton",
        color: "black",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
         mainImage: '/imgs/5.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 6,
        name:'Pretty hat',
        frontShape: "slightly",
        Closure: "snapback",
        material: "cotton",
        color: "blue",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/7.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 7,
        name:'Pretty hat',
        frontShape: "slightly",
        Closure: "buckle",
        material: "cotton",
        color: "yellow",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/6.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 8,
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "fitit",
        material: "cotton",
        color: "gray",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/7.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 9,
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "velcore",
        material: "cotton",
        color: "black",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/8.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 10,
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "snapback",
        material: "cotton",
        color: "blue",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/9.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 11,
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "buckle",
        material: "cotton",
        color: "yellow",
        size: ["Small","Medium" ,"Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/10.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    },
    {
        id : 12,
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "fitit",
        material: "cotton",
        color: "yellow",
        size: ["Small","Large","X-Large"],
        price: 20.99,
        mainImage: '/imgs/8.png',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: '',
        desc:"This is the description filler has not any value in it it is here just to fill the space",
        quantuty:25,
        madein:"USA",
        bulletone:"bullet fillet",
        bullettwo:"bullet filler two",
        bulletthree:"bullet filler three"
    }
]