export const VARIATIONSOFITEMS = [
{
        id:1,
        mainItemId: 1,
        size: "XL",
        color: "blue",
        mainImage: "/imgs/3.png",
        childimage1: "/imgs/3.png",
        childimage2: "/imgs/3.png",
        childimage2: "/imgs/3.png",
        childimage2:"/imgs/3.png",
        quantity:50,
        price:45.99
    },
{
        id:1,
        mainItemId: 1,
        size: "S",
        color: "blue",
        mainImage: "/imgs/2.png",
        childimage1: "/imgs/2.png",
        childimage2: "/imgs/2.png",
        childimage2: "/imgs/2.png",
        childimage2:"/imgs/2.png",
        quantity:50,
        price:90
    },
   {
id:1,
        mainItemId: 1,
        size: "M",
        color: "red",
        mainImage: "/imgs/4.png",
        childimage1: "/imgs/4.png",
        childimage2: "/imgs/4.png",
        childimage2: "/imgs/4.png",
        childimage2:"/imgs/4.png",
        quantity:50,
        price:30
    },
   {
id:1,
        mainItemId: 1,
        size: "L",
        color: "yellow",
        mainImage: "/imgs/5.png",
        childimage1: "/imgs/5.png",
        childimage2: "/imgs/5.png",
        childimage2: "/imgs/5.png",
        childimage2:"/imgs/5.png",
        quantity:50,
        price:50.99
    },
   {
id:1,
        mainItemId: 1,
        size: "S",
        color: "black",
        mainImage: "/imgs/6.png",
        childimage1: "/imgs/6.png",
        childimage2: "/imgs/6.png",
        childimage2: "/imgs/6.png",
        childimage2:"/imgs/6.png",
        quantity:50,
        price:28.99
    },
   {
id:1,
        mainItemId: 1,
        size: "M",
        color: "orange",
        mainImage: "/imgs/7.png",
        childimage1: "/imgs/7.png",
        childimage2: "/imgs/7.png",
        childimage2: "/imgs/7.png",
        childimage2:"/imgs/7.png",
        quantity:50,
        price:38.99
    }
]