export const ADD_ITEMS = 'ADD_ITEMS';
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const ITEMS_FAILED = 'ITEMS_FAILED';

export const ADD_VAR = 'ADD_VAR';
export const LOAD_VAR = 'LOAD_VAR';
export const VAR_FAILED = 'VAR_FAILED';

export const ADD_TO_CUSTOMIZE = 'ADD_TO_CUSTOMIZE';
export const REMOVE_FROM_CUSTOMIZE = 'REMOVE_FROM_CUSTOMIZE';
export const REMOVE_ALL_FROM_CUSTOMIZE = 'REMOVE_ALL_FROM_CUSTOMIZE';
export const ADD_MANUALL_NUMBER_TO_CUSTOM = 'ADD_MANUALL_NUMBER_TO_CUSTOM';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_MANUALL_NUMBER_TO_CART = 'ADD_MANUALL_NUMBER_TO_CART';



export const SEND_CUSTOM_IMAGE_TO_REDUCER = 'SEND_CUSTOM_IMAGE_TO_REDUCER';